name: test_app_flutter
description: Test
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.12.0+3

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:

  keycloak_flutter: any

  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
